### ISSUE TITLE
Receive push notifications for hardware wallet keys

### ISSUE THREAD

**Issue by sche** [gnosis/safe#458] opened 2021-07-22 13:28 UTC
# What is this feature about? (1 sentence)
Users that add ledger keys on mobile should receive push notifications the same way as users that import/generate keys on mobile.

# Why is it needed? What is the value? For whom do we build it?
There are some users that do not trust to store their keys on mobile. If they import a hardware wallet key, they should have the same convenience level as other app users.

# High-level overview of the feature
Now we sign the register for push notifications payload with phone keys on every app start and after some user actions.
With hardware wallet keys it is not possible as we would need to request user permission every time we want to send a request.
We need to find a way to register/unregister for push notifications that would work for hardware wallet keys.

**Comment by DmitryBespalov** [comment] 2021-09-01 12:28
duplicate of #484

**Closed as completed by DmitryBespalov** 2021-09-01 12:28 UTC
