### ISSUE TITLE
Align Send Funds flow

### ISSUE THREAD

**Issue by posthnikova** [gnosis/safe#38] opened 2018-12-19 10:01 UTC
Redesigning iOS as part of integration proposal. Current designs put for review here: https://invis.io/FBPH0OFQ57P. Previous version for history: https://docs.google.com/presentation/d/1bgn9qh_HWq0poTdxORHkz580B3nKt50tJF6ySZnZXvo/edit#slide=id.g49dff9ba04_0_60

**Comment by posthnikova** [comment] 2018-12-20 16:38
What's been done in new iteration:

1. Concerning this screen: https://invis.io/FBPH0OFQ57P#/336311495_05_Send-ETH-Review_. There was a comment that progress bar is misleading. New version of this screen: https://invis.io/FBPH0OFQ57P#/337647708_38_Send-ETH-Review_With_Resend_. Other states for this screen: confirmed https://invis.io/FBPH0OFQ57P#/337647727_40_Send-ETH-Confirmed_With_Resend_ and rejected https://invis.io/FBPH0OFQ57P#/337647735_41_Send-ETH-Rejected_With_Resend_. Also on small screens the button should be fixed at the bottom because content does not fit on screen: http://joxi.net/nAyYZX3fY6GOYA. 

2. For the same screen there's a version with Resend button and countdown: https://invis.io/FBPH0OFQ57P#/337647708_38_Send-ETH-Review_With_Resend_.

3. Concerning this screen: https://invis.io/FBPH0OFQ57P#/336311497_07_Send-ETH-Review-Reminder-Small-Screen_. There was a comment that overlay text is unreadable. Here's a version with blurred background: https://invis.io/FBPH0OFQ57P#/337570861_36_-3x_Send-ETH-Review-Reminder_Blur

4. Concerning this screen: https://invis.io/FBPH0OFQ57P#/336311504_14_Send-Token-Review_. There was a comment that text could be optimized. Here is a version with less text: https://invis.io/FBPH0OFQ57P#/337590007_37_Send-Token-Review_Less_Text_-3x. 

5. On this screen: https://invis.io/FBPH0OFQ57P#/336311492_04_Send-ETH-InfoModal_ the wording is corrected

**Comment by tschubotz** [comment] 2018-12-21 09:43
Regarding 1:
- I like the removal of the progress bar. If we go with this version, Android need to adapt too though. @biocom what do you think?
- The [rejection screen](https://projects.invisionapp.com/share/FBPH0OFQ57P#/screens/337647735_41_Send-ETH-Rejected_With_Resend) should not have a "submit" button, but instead the resend button enabled.

Regarding 2:
- Isn't that the same screen you link in "1"? I don't see any difference.

Regarding 3:
- If we remove the progress bar, this screen has to change as well, right?

Regarding 4:
- I like it, removes duplicate information.

Regarding 5: 
- 👍

**Comment by posthnikova** [comment] 2019-01-03 09:37
New iteration put for review here: https://invis.io/FBPH0OFQ57P 

Replying to @tschubotz comments above (https://github.com/gnosis/safe/issues/38#issuecomment-449334901):

1. Concerning new version of Send ETH screen without progress bar: https://invis.io/FBPH0OFQ57P#/337647708_38_Send-ETH-Review_With_Resend_. 1) If we go with this version, Android would have to adapt as well. 2) Rejection screen corrected: https://invis.io/FBPH0OFQ57P#/337647735_41_Send-ETH-Rejected_With_Resend_. 
Also added card-based version of the same: https://invis.io/FBPH0OFQ57P#/338853240_42_Send-ETH-Review_With_Resend_ 

2. Yes it's the same screen

3. Yes, if we remove the progress bar this has to change. I'm keeping this version for history to know where we come from

Other changes:

1. Concerning this overlay with reminder: https://invis.io/FBPH0OFQ57P#/336311496_06_Send-ETH-Review-Reminder_. If we remove the progress bar this screen has to change, here is the new version:  https://invis.io/FBPH0OFQ57P#/338856342_44_Send-ETH-Review_Reminder_. And for iPhone 5 as well: https://invis.io/FBPH0OFQ57P#/338856345_45_Send-ETH-Review_Reminder_IPhone5_ 

2. Concerning Send Token Review version with less text: https://invis.io/FBPH0OFQ57P#/337590007_37_Send-Token-Review_Less_Text_-3x. We go with this version so I updated it everywhere. And the wording on Send Token screens has to be corrected too: https://invis.io/FBPH0OFQ57P#/336311654_26_Send-Token_.

**Comment by posthnikova** [comment] 2019-01-10 17:12
New iteration put for review here: https://invis.io/FBPH0OFQ57P

What's been done:

General comments:
- Made the shadows less blurry throughout the app (on nav bar and cards)
- Made button’s shadow less prominent

1. Concerning Send Token Review screens. This is the main version now: https://invis.io/FBPH0OFQ57P#/339971945_05_Send-ETH-Review_ (white backgroud with new illustration and reminder on card). We use cards only when we need to emphasise some information 

2. Concerning this screen: https://invis.io/FBPH0OFQ57P#/339971947_07_Send-ETH-Confirmed_. 
Just a reminder that there won't be "Finish" button in the future so there won't be need for double confirmation from the user

3. On all Send screens "Safe balance" changed to "Current balance": https://invis.io/FBPH0OFQ57P#/339971941_01_Send-ETH_. On android should be corrected too cc @biocom 

4. On Rejected screen button renamed to "Resend" (previously was "Resubmit"): https://invis.io/FBPH0OFQ57P#/339971949_09_Send-ETH-Rejected_5. Concerning https://invis.io/FBPH0OFQ57P#/336311504_14_Send-Token-Review_. There is a version without icon here: https://invis.io/FBPH0OFQ57P#/339971963_21-Send-ETH-Review_W-O_Icon_. I also made alternative version where amounts are one under another: https://invis.io/FBPH0OFQ57P#/339971964_22_Send-ETH-Review_Version_.

**Comment by DmitryBespalov** [comment] 2019-01-14 16:31
commented in Invision

**Comment by posthnikova** [comment] 2019-01-24 13:54
Final version put for review here: https://invis.io/FBPH0OFQ57P 

Main changes: transaction fees changed to network fees everywhere, added error states, recipients field is now not editable manually, also decided on how we display digits.

**Comment by DmitryBespalov** [comment] 2019-01-24 15:48
👍

**Comment by tschubotz** [comment] 2019-01-24 16:14
Commented on Invision. 💬

**Comment by posthnikova** [comment] 2019-01-25 14:48
I replied to everyone and made changes: https://invis.io/FBPH0OFQ57P

**Comment by biocom** [comment] 2019-01-25 14:54
Was wondering if we should change the placeholder text from 'Recipient's address' to 'Choose recipient address' as that sounds more like a call to action + potentially removes the expectation that it's an inputfield? See my example for Android:
https://invis.io/ARPG0XSTJMZ#/336852732_22_Send_Token_Entered_-_5

**Comment by tschubotz** [comment] 2019-01-28 10:49
There are quite some differences between Android and iOS

iOS: https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897/screen/5c4b2fe44def2a015baf61e7
Android: https://projects.invisionapp.com/share/FBPH0OFQ57P#/screens/339971943/

**Comment by tschubotz** [comment] 2019-01-28 10:53
There are still some differences between Android and iOS. We should align on them @biocom @posthnikova 

Android: https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897/screen/5c4b2fe44def2a015baf61e7
iOS: https://projects.invisionapp.com/share/FBPH0OFQ57P#/screens/339971941/

- On Android, we show the identicon, on iOS we don't - I think we should go with the Android solution.
- On iOS we have a "back" button, on Android a cancel - I think the Android cancel makes more sense.
- Android doesn't have the "?" button to explain network fee - Could we add it?
- "Recipient's Address" vs. "Recipient address"

Besides on the iOS reciew screen, we still show the Current balance twice, on Android we don't. I think it's not necessary (https://projects.invisionapp.com/share/FBPH0OFQ57P#/screens/339971945/)

**Comment by biocom** [comment] 2019-01-28 11:46
**Update:** 
https://invis.io/CSPVFSH7QUN
https://invis.io/J4Q757769AZ
https://invis.io/45Q757CWNDY

Changelog:
- Added the [?] button
- Changed to 'Recipient's address'

**Comment by tschubotz** [comment] 2019-01-28 16:01
Thanks for the changes, looks good.

Concerning the identicon on iOS @posthnikova: Yes, there is no address book yet, however the identicon is derived just from the address, so we don't need the address book for that. I think we could and should display it already right away.
For the [empty state](https://invis.io/FBPH0OFQ57P#/339971961_19_Send-ETH_With_Address_Book) I think we should then just leave out the icon and move the text to the left. What do you think?

And for the specific other transaction types - good catch! For them I would add the balance then. But leave it out for transfers. Does that make sense @posthnikova @biocom ?

Concerning @rmeissner 's [comment](https://projects.invisionapp.com/share/FBPH0OFQ57P#/screens/339971945/comments/109884318): It's mainly about data transactions from e.g. the browser extension. Theoretically, as part of the function call, ETH could be transferred. We wouldn't be able to show that to the user upfront. But I think there is still value to show the balance, even if it's not accurate in all of the cases, since the alternative would be showing no balance at all. Does that make sense? 


Unrelated to the above, the top part still differs:
![image](https://user-images.githubusercontent.com/1380529/51848167-5b0b4600-231d-11e9-8aec-0e480fd89ccb.png)
vs.
![image](https://user-images.githubusercontent.com/1380529/51848173-5fcffa00-231d-11e9-8b7f-ef0b3b010b5d.png)

That's due to the fact that on iOS there is only 1 Safe I assume?
How about still going with the Android approach so we don't have to change it later once multiple Safes are supported on iOS?

**Comment by posthnikova** [comment] 2019-01-28 16:25
1) I agree to add identicon now (it's not going to be interactive for now). Also also for empty state is fine not to display it. 

2) Makes sense to add current balance only on specific transaction types.

3) So I'll keep "Balance after transfer" everywhere

4) This is due to the fact that on iOS we only have one Safe and also we don't have custom Safe names. So it's going to look like this: https://invis.io/FBPH0OFQ57P#/339971962_20_Send-ETH-Filled_With_Identicon_

**Comment by tschubotz** [comment] 2019-01-28 16:50
Yes, we'll have multiple Safes in the future. It might be > 4 months down the line though. 

And I would use Sasha's [screen with the identicon](https://invis.io/FBPH0OFQ57P#/339971962_20_Send-ETH-Filled_With_Identicon) already to be honest.

What about the following things on the header bar:
- "Send" or "Send ETH"? - I vote for the latter to be explicit. What do you think?
- "Cancel" or "Back"? - If we imagine the screen to "pop up", then I'd go for "cancel", if it "slides in from the right", then I'd go with back. Which way do you imagine it to happen?

**Comment by tschubotz** [comment] 2019-01-29 09:19
> I can make two versions of this header, one of them for the future. We'll also have to update overview screen and menu.
• Send ETH is more clear to me.

👍 

> And everywhere else should be "Cancel" because you can't edit fields at this point, you cancel everything and return to Overview assets.

So you are saying that e.g. [this screen](https://projects.invisionapp.com/share/FBPH0OFQ57P#/screens/339971960) should have cancel button? I disagree. There should be a back button since you can actually go back and edit things.

Back vs. cancel: I'm fine either way. Your reasoning on "back" makes sense to me. @biocom do you agree with that for Android?

**Comment by biocom** [comment] 2019-01-29 10:11
So for example on a screen like https://zpl.io/am93qq6 you mean we'd have a back button? I think if leaving this view 'resets' any user inputted data, we'd need to make it more explicit that you're cancelling and not just simply 'go back' ?

**Comment by posthnikova** [comment] 2019-01-29 12:59
> So you are saying that e.g. this screen should have cancel button? I disagree. There should be 
> a back button since you can actually go back and edit things.

If from Review screens you can go back to edit fields there should be "Back" link (it is now). I thought you can't at this point.

> So for example on a screen like https://zpl.io/am93qq6 you mean we'd have a back button? I
> think if leaving this view 'resets' any user inputted data, we'd need to make it more explicit
> that you're cancelling and not just simply 'go back' ?

I'm for "Back" link in this case because you don't cancel transaction. Also it has to do with the animation screen appears with. On iOS it slides from the left. On android it's like overlay screen and you close it.

Other changes uploaded here: https://invis.io/FBPH0OFQ57P

**Comment by tschubotz** [comment] 2019-01-29 14:03
> If from Review screens you can go back to edit fields there should be "Back" link (it is now). I thought you can't at this point.

Yes you can :)
Only during Safe creation, you cannot go back after the address has been calculated.

> I'm for "Back" link in this case because you don't cancel transaction. Also it has to do with the animation screen appears with. On iOS it slides from the left. On Android it's like overlay screen and you close it.

Agree, depends on the animation. But then we should really unify the animation.

[Changes](https://invis.io/FBPH0OFQ57P) look good! 

Now there is quite some wording differences on the review screen still ([Android](https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897/screen/5af0646aa735b50924a6712e), [iOS](https://projects.invisionapp.com/share/FBPH0OFQ57P#/screens/339971946))
- "Review" vs "Review transaction" -> I think just "Review" is fine.
- "Open browser extension to confirm this transaction" vs "Confirm this transaction with the browser extension" -> I prefer the former since it tells the user to first open the extension.
- "Resend" vs. "Re-send" -> I prefer resend.

Confirm state: ([Android](https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897/screen/5af0646b3645d6cf66edba2b), [iOS](https://projects.invisionapp.com/share/FBPH0OFQ57P#/screens/339971947))
- Android is missing the nice illustration.
- I think Android should take text from iOS as well.

Same for the rejected state ([Android](https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897/screen/5afea89d7e031a4693bf0a2d), [iOS](https://projects.invisionapp.com/share/FBPH0OFQ57P#/screens/339971949))

**Comment by tschubotz** [comment] 2019-02-14 10:36
changes are made after user testing of review screen. #108

**Comment by posthnikova** [comment] 2019-02-15 17:08
Changes after user tests are up for review https://invis.io/FBPH0OFQ57P. What's been done:

1) "Awaiting confirmation" changed to "Authentication required": https://invis.io/FBPH0OFQ57P#/339971945_05_Send-ETH-Review_

2) "To Review" changed to "Review": https://invis.io/FBPH0OFQ57P#/339971941_01_Send-ETH_

3) Animation updated:


![send_animation.gif](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/ec05a9a2-3a2a-4fcb-943f-22e8bdd92af8)


4) Removed redundant actions on Congratulations screen: https://invis.io/FBPH0OFQ57P#/344732516_19_Congratulations

Other changes after feedback:

- Input fields now have red border on error screens (exclamation mark is not used): https://invis.io/FBPH0OFQ57P#/341522165_03_1_Send-ETH-Filled-Errors

- Andrey @sche pointed that soon there will be no 30 sec timer and you'll be able to tap Submit as many times as you like. So this is the version: https://invis.io/FBPH0OFQ57P#/347141387_22_Send_ETH_Review_W-Submit_

**Comment by tschubotz** [comment] 2019-02-18 12:57
Why will there be no 30s timer soon? @posthnikova

**Comment by tschubotz** [comment] 2019-02-20 10:16
Just had a chat with Andrey on this. Here are the notes:
- On iOS we don't have this timer and the resend button, but instead show the enabled submit button immediately. If a user presses that button, then there is an alert that the confirmation is missing and they cannot continue, yet. After the user tapped that button, the push is resent again after 30s. Minette was involved in coming up with this solution. I'm not sure if there was a user test. At least I didn't see any insight docs about it.
- Another argument (I think the main one) for hiding it more: Usually it shouldn't happen, that the user needs to resend the push. So there is no need to put it so prominently.

I think this solution could work too, however the following things are important to me:
- Does that solution even work? i.e. if the user didn't receive the push on their extension, do they know that they have to hit the "submit" button to re-trigger the push instead of a specific "resend" button?
- I would like to have the same version on both platforms. I see no need to deviate.

-> Let's discuss on our UX weekly sync tmr. I put it on the agenda.
cc @posthnikova @biocom @lukasschor

**Comment by biocom** [comment] 2019-02-20 15:05
Latest Android screens up for review: https://invis.io/MPQM3WM4DSX

**Comment by tschubotz** [comment] 2019-02-21 10:57
UX weekly notes:
- In other apps: When we wait for a push, there's a lot of insecurity about where the push is. So we should have the button up front actually. Gives also a sense of control.
-> Explicit button is favored.

@sche The majority at the UX sync felt that way ☝️

**Comment by posthnikova** [comment] 2019-02-21 15:46
Changes to iOS: https://invis.io/FBPH0OFQ57P

Added Submit button on review screen and Resend popup. Also aligned text highlighting with android.

**Comment by tschubotz** [comment] 2019-02-22 09:41
One thing we haven't discussed during the UX weekly: How do you feel about (additionally) adding a submit button to the navbar on the review screen? 
- We have the CTA there on quite some other screens.
- It won't be hidden on small devices.
What do you think @posthnikova ?

**Comment by sche** [comment] 2019-02-22 13:21
@tschubotz @posthnikova also take in mind review transaction screen for the cases when browser extension confirmation is not needed. How the submit button will look like?

**Comment by posthnikova** [comment] 2019-02-22 13:48
> One thing we haven't discussed during the UX weekly: How do you feel about (additionally) 
> adding a submit button to the navbar on the review screen?

I'm not against it. But the action in nav bar could distract from instructions to confirm with browser extension. 

> also take in mind review transaction screen for the cases when browser extension confirmation 
> is not needed. How the submit button will look like?

There is a version for this case: https://invis.io/FBPH0OFQ57P#/339971958_14_Send-Token-Review-NoExtension

**Comment by tschubotz** [comment] 2019-02-26 16:33
UX weekly sync outcome: Just have 1 CTA. The big blue buttons is enough. This was also confirmed in user testing.

**Comment by biocom** [comment] 2019-02-27 12:23
Android production screens:
https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897/dashboard?seid=5c4b3083b09a3dbffc875566

**Comment by posthnikova** [comment] 2019-02-27 16:03
Error state is updated after UX meeting: https://invis.io/FBPH0OFQ57P#/341522165_06_Send_ETH_Filled_Errors

Zeplin for ios is here:

zpl://project?pid=5c49ce9866e3b3bee966f431&seid=5c76b3a54e848abc6c5543ee

https://app.zeplin.io/project/5c49ce9866e3b3bee966f431/dashboard?seid=5c76b3a54e848abc6c5543ee

**Comment by biocom** [comment] 2019-03-01 08:30
Looks good. One point:
- Do we add the 3 dots to the address on these screens too? -> https://zpl.io/VQBQ00n
iOS is missing this (at least on Zeplin).

**Comment by posthnikova** [comment] 2019-03-01 12:01
I didn't add 3 dots here, it's not the purpose of this step to make actions with address

**Comment by biocom** [comment] 2019-03-01 12:02
Just a question: Why is that purpose different from the purpose on the transaction details?

**Comment by posthnikova** [comment] 2019-03-01 12:08
If you wander from this screen you won't submit transaction

**Comment by lukasschor** [comment] 2019-03-01 12:11
I can see the point to add the three dots for consistency. But I agree with Sasha that at this step the user should not be distracted from the main action (submitting the transaction).

**Comment by biocom** [comment] 2019-03-01 12:31
Yes, I think Sasha made a valid point. Updated the screens on my end:
https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897/dashboard?seid=5c4b3083b09a3dbffc875566

**Comment by tschubotz** [comment] 2019-03-27 14:42
Reopening this since there are some missing screens and inconsistencies:
The Android ticket was #43 but I thought it makes more sense to have now everything in one ticket:

(1) 
- I couldn't find the Android screen when sending ETH and no input field is filled out. 
- The iOS screen is https://zpl.io/2yO6vpG
- @biocom Could you please create one?

(2)
- I couldn't find the Android screen when all info is filled in and no address from the address book was used.
- The iOS screen is https://zpl.io/adpXvLR
- @biocom could you please create this screen for Android?

(3) 
- On iOS, why is the submit button in a different place when there is [no 2FA configured](https://zpl.io/2ZLd1j1) as opposed to [when 2FA is configured](https://zpl.io/aR1A8Wv)?
- Android has it in the same place.
- @posthnikova Could you please change it so the big submit button is also used when there is no 2FA configured?

(4)
- When getting to the review screen initially (and 2FA is configured), then on Android we disabled the submit button and have countdown that goes down: https://zpl.io/29OjqNW. On iOS we have the button enabled (https://zpl.io/aBBnDyK) and there is a [popup](https://zpl.io/aXPp8wX) when tapping the button. Why is it different?
- @posthnikova could you please change it and use the Android approach?

(5)
- When a token is transferred and ETH is used as payment token, there is a bit more info on the screen. I was missing some screens on Android, for completeness reasons.
- @biocom could you please create the Android screens for the following iOS screen?
  - https://zpl.io/aBBnDRL
  - https://zpl.io/beDmpAm
  - https://zpl.io/VkGLvpZ

**Comment by tschubotz** [comment] 2019-03-28 10:58
UX sync:
Ideal way, UX wise:
- No prominent Submit button if there's nothing to submit
- Timer creates unnecessary urgency, so let's remove it.
- User could tap resend any time, but App should make sure it's not resend immediately to prevent multiple notifications showing up on the extension.

@tschubotz to clarify with iOS and Android team if there's any technical issues with that and then let @posthnikova @biocom know.

**Comment by sche** [comment] 2019-03-28 11:09
No technical issues on the iOS side.

**Comment by posthnikova** [comment] 2019-03-28 13:16
3) Submit button corrected https://zpl.io/2ZLd1j1, https://zpl.io/VOPAN4Y

4) Changed to Resend link without timer https://zpl.io/aBBnDyK, https://zpl.io/VkGLvpZ

**Comment by tschubotz** [comment] 2019-03-29 14:02
> @tschubotz to clarify with iOS and Android team if there's any technical issues with that and then let @posthnikova @biocom know.

As Andrey said, not technical issue on iOS. On Android neither.

**Comment by biocom** [comment] 2019-03-29 14:23
1) Added: https://zpl.io/am93qq6
Also noticed that the input alignment for the amount, differed between Android and iOS. After discussing with @posthnikova I chose to adapt to iOS: https://zpl.io/bAZR888

2) A screen with validation errors existed already in https://zpl.io/VKPDv18 but also created one without validation errors here https://zpl.io/aNPRYpe

5) Added:
https://zpl.io/adp8nYl
https://zpl.io/VKPYJQJ
https://zpl.io/a7OYDvR
Some changes:
- Create more of a visual separation between the token balances and the payment method balances.
- No duplication of token symbols in the descriptions and describe what kind of balance it is (also evades changes of having symbols with more characters). E.g.:
 Current balance (ETH) ----------> Payment method balance
 ETH Balance after transfer -----> Balance after transfer
@posthnikova Had some doubts on the balances layout. Let's discuss them here or in a next UX sync.

X) Other:
- Removed 30sec timer for submitting a tx. again.

**Comment by biocom** [comment] 2019-04-01 16:03
@tschubotz @posthnikova As for the screens/comments tied to point 3. in my last comment: Can you review and let me know your thoughts? I think after that is done, we could close this ticket.

**Comment by tschubotz** [comment] 2019-04-02 09:56
I'm still missing the tx review screen when paying with tokens :) (iOS: https://zpl.io/VkGLvpZ)

Concerning the wording, I like the proposals. Let's decide in the UX sync.

**Comment by biocom** [comment] 2019-04-02 10:09
Those are there, see my comment with point 3. on it :)

**Comment by tschubotz** [comment] 2019-04-02 10:21
UX sync: 
- Let's not display the payment method balance
- Let's remove duplication of ETH

**Comment by posthnikova** [comment] 2019-04-02 14:17
Duplicate ETH removed on iOS:

https://zpl.io/aBBnDRL Send Token Empty fileds

https://zpl.io/beDmpAm Send Token filled

https://zpl.io/VkGLvpZ Send Token Review

https://zpl.io/VOPAN4Y Send Token Review Without Extension

https://zpl.io/VKPDgg6 Send Token Confirmed

https://zpl.io/bABdq0P Send Token Rejected

We don't have minuses near network fee anymore, I just noticed I still have them in some flows. 
@biocom could you please also make sure you don't have minuses

**Comment by biocom** [comment] 2019-04-03 12:37
Updates:
- Added the reviews screens for the tokens payments now 💰 ...:
https://zpl.io/aNPd0Mv
https://zpl.io/aBBe5Dm
- Updated the token payment screens (balance section) in general, based on our last UX sync meeting.
- Send Token - Extension/Confirmed > https://zpl.io/beDrY9W
- Send Token - Extension/Rejected > https://zpl.io/VqWGE7m

**Comments:**
- iOS screen https://zpl.io/beDmpAm still contains the (ETH) text.
- Checked for negative (minus) text strings and it's not present anymore on Android. @posthnikova thank you for double checking this and bringing this up.
- As for a screen like the 'Replace recovery phrase' (https://zpl.io/bzNvWvM) I wonder if we need also screens to indicate when you pay with a token. Or should we leave as is and just replace the values of 'Network fee' and 'Balance after transfer'?

**Comment by posthnikova** [comment] 2019-04-03 14:58
> iOS screen https://zpl.io/beDmpAm still contains the (ETH) text.

Corrected https://zpl.io/beDmpAm

> As for a screen like the 'Replace recovery phrase' (https://zpl.io/bzNvWvM) I wonder if we 
> need also screens to indicate when you pay with a token. Or should we leave as is and 
> just replace the values of 'Network fee' and 'Balance after transfer'?

Do you mean paying transaction fees in tokens? Yes we need screens for this. The selected payment method will apply here but you'll be able to change it like in Send flow (https://invis.io/3XQVZ474E9U#/350900047_06_Send_ETH_Filled).

**Comment by lukasschor** [comment] 2019-04-11 09:51
UX Sync: Remove one "Balance after transfer" in case the same token is used for fees.

**Comment by biocom** [comment] 2019-04-15 15:54
Some updates:
- Updated all the screens on Zeplin: [Send Funds](https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897/dashboard?seid=5c4b3083b09a3dbffc875566)
- Added screen which shows a tooltip over the token feature: https://zpl.io/VQvqN7k 
  The idea being we'd show this tooltip the first time the user opens a Send [Token] screen. @lukasschor screen needs a new tracker name.
- Added the 'Payment Method' screen purposed for the Send [Token] screen: https://zpl.io/VOxWvwl  
 @posthnikova We need it for iOS too. @lukasschor This screen needs a new tracker name. This screen is used also in other flows. Do we need multiple instances of this same screen for tracking purposes or do we use only this one?

**Comment by lukasschor** [comment] 2019-04-16 10:18
> Added the 'Payment Method' screen purposed for the Send [Token] screen: https://zpl.io/VOxWvwl
@posthnikova We need it for iOS too. @lukasschor This screen needs a new tracker name. This screen is used also in other flows. Do we need multiple instances of this same screen for tracking purposes or do we use only this one?

@biocom Should be fine if we only have one tracking key for this screen. Will update the name on Zeplin.

**Comment by posthnikova** [comment] 2019-04-23 10:35
> Added the 'Payment Method' screen purposed for the Send [Token] screen: 
> https://zpl.io/VOxWvwl @posthnikova We need it for iOS too

@biocom Token payment hasn't been approved for development and might change after user tests. I will upload it on Zeplin once approved. Do we need to decide on tracking names now?

**Comment by posthnikova** [comment] 2019-05-02 13:31
Small changes from UX sync are done on iOS: https://app.zeplin.io/project/5c49ce9866e3b3bee966f431/dashboard?seid=5c76b3a54e848abc6c5543ee

Removed exclamation icon on insufficient funds, wording changed to "Rejected BY the browser extension". Screen names did not change.

We need Android version without token payment on Zeplin and then we can complete the checklist for closing.

**Comment by biocom** [comment] 2019-05-02 16:30
Updated the Zeplin screens for Android:
- https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897/dashboard?seid=5c4b3083b09a3dbffc875566

One new screen is also the OFFLINE state. For Android I'm thinking to keep the same style we use for the Snackbars (bottom): https://app.zeplin.io/project/5af063c9b4dc859b6bdaf897/screen/5ccb17ad41eeab347eab0922
I think saying 'This app is offline' is commonly used. What do you think of using that text string? 

@lukasschor Also tagging screens which need a title with 'Needs Screen ID!'.

**Comment by lukasschor** [comment] 2019-05-02 16:35
@biocom I actually like this no offline warning (especially the retry button), but if we implement it that way it should be aligned across screens and platforms. What do you think @posthnikova?

Also added the screen ID in the description.

**Comment by posthnikova** [comment] 2019-05-03 09:44
@lukasschor The message doesn't look like an error. "This app is offline" could mean a setting of some sort, like offline mode, or like it saves inputs locally (not in the cloud). Also maybe because of icon. I like the Retry button.

**Comment by biocom** [comment] 2019-05-03 09:56
@posthnikova @lukasschor In my view, this shouldn't be classified as an 'error' but rather a (soft) warning. Being offline can be a deliberate choice of the user and not a cause effect of an user- or app error. 

As for the cloud icon: Saw it being used on several examples. Also the WIFI icon (not sure that represents mobile internet correctly). Placing the banner on top (for offline states) seems a common pattern on Android. @posthnikova How would you rather have it for iOS?

**Comment by lukasschor** [comment] 2019-05-03 10:03
Agree with @biocom 's reasoning

@KristinaMayman As far as I can remember, you were also in favour of having a less red color. :) What do you think?

**Comment by KristinaMayman** [comment] 2019-05-03 10:13
The new screen is definitely easier on the eyes :) I prefer this softer version, but as I said, would be curious to see how users would react to seeing either of the two options (red or dark blue).

**Comment by lukasschor** [comment] 2019-05-03 10:15
@KristinaMayman Looks like this could be a good case for some spontaneous hallway-testing at Full Node. :P

**Comment by posthnikova** [comment] 2019-05-03 10:48
I like the banner on top. Examples of how other apps do this:
All google apps have message at the bottom: https://prnt.sc/njvcd9 (hides after a moment, no icon).
Dropbox: https://prnt.sc/njvbjx (persistent but has cross, icon is wi-fi). 
Yandex.mail: https://prnt.sc/njvc4x (hides after a moment, icon is exclamation sign). 
N26: https://prnt.sc/njvcmi (hides after a moment, icon is bell). 
Messenger: https://prnt.sc/njvdah (persistent).
Instagram: https://prnt.sc/njvdkx (hides after a moment). 

If we do persistent message I'd go with grey and provide a cross to close https://prnt.sc/njvhgm. Retry button is also nice https://prnt.sc/njvhnb. Wording could be "No connection" or "This app is offline".

If we do message which hides I'd go with more prominent red without cross to close https://prnt.sc/njvhyh. 

Also it has to be the same height as rinkeby message because it shows on top of it. So we don't have to shift content differently in that case.

As for the icon - I think having cross, "Retry" and icon at the same time would be too much. If we don't have any of these, icon would be fine

**Comment by posthnikova** [comment] 2019-05-06 14:42
After discussing with Lukas: 

We propose persistent message with reload button. On ios - same size as Rinkeby warning, white text on blue (like educational tooltips), capitalised, white Reload icon. The wording is "This app is offline". On android - the same but keep dark blue background. @biocom do you have any objections? 

![02_Send_Input (no internet) Copy 2.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/0bfb04d9-85ca-4070-9fb4-1e2dbeb6de68)

**Comment by biocom** [comment] 2019-05-06 15:18
@posthnikova In general no objections, just two questions based on a version I have for Android https://zpl.io/bJpJNxx
- iOS doesn't have a cloud/wifi icon. Are we ok with having it on Android?
- Android uses an explicit 'Retry' text label. Your iOS proposal uses an icon. Are we ok with the difference or should we re-align?

**Comment by lukasschor** [comment] 2019-05-06 15:26
1) I would leave it out. I liked the icon, but given the requirements (same size as rinkeby warning & text center-aligned), I would say it works better without.
2) I would also re-align android on the retry icon. 

@biocom Does that work for you?

**Comment by biocom** [comment] 2019-05-07 07:43
In general works for me. Although I would left align the text for Android for two reasons:
- It's a common pattern used on Android to left align text and have the 'action' (icon) right aligned.
- Assuming we'd have additional languages in the future, center aligning text can be unpredictable in terms of the text width (touching the icon). Left aligning mitigates this to some extent. If we'd have **no** icon, center aligning the text would be no issue.

Updated screen: 
https://zpl.io/bJpJNxx

**Comment by lukasschor** [comment] 2019-05-10 10:22
@posthnikova @biocom 

Can you also make go through the checklist for this ticket and if everything is fine, I'll upload the screens that change through alignment to Lokalise.

**Comment by lukasschor** [comment] 2019-05-10 15:39
As discussed on slack, this ticket can be closed.

**Closed by lukasschor** 2019-05-10 15:39 UTC
Labels: android, design, ios, ui
